apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uchenewwebsit-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Youngyz1/Terraform-ECR-EKS-Deploy.git
    targetRevision: main
    path: manifests/production
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
